---
title: "women_participation"
author: "Madeline Gorchels"
date: "11/9/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
```

Here is a good resource I found for adding widgets to a Shiny app and using them: https://shiny.rstudio.com/tutorial/written-tutorial/lesson3/


```{r, include=FALSE}
#reading in packages and data 
library(tidyverse)
library(effsize)
library(kableExtra)
library(lubridate)
library(vcd)

w_p = read_csv("women_participation_git_fix.csv") %>% 
  mutate(class = as.factor(class)) %>% #changing class column to a factor instead of a continuous integer
  mutate(time = as.ordered(time))

#View(w_p) #calling the data frame 
```

```{r}
#Data Exploration
w_df = w_p %>% 
  filter(student_g_p == "w")
#View(w_df)
m_df = w_p %>% 
  filter(student_g_p == "m")
#View(m_df)

#Calculating general propotions in man presenting and woman presenting students
#male proportion of the cohort is 0.3108
prop_w = count(w_df)/(count(w_df)+count(m_df))
#prop_w
prop_m = count(m_df)/(count(w_df)+count(m_df))
#prop_m
prop_m

```

```{r}
sum_df = w_p %>% 
  group_by(student_g_p)
  #summarise(
    #count_time = count(time) 
    #count_answer = count(q_or_a)
  
```

```{r}
# exploratory time series graph of counts of participation by date


p_by_date <- w_p %>% 
  mutate(date = mdy(date)) %>% 
  select(date, student_g_p, class)

ggplot(p_by_date, aes(x = date)) +
  geom_bar(aes(fill = student_g_p)) +
  scale_fill_manual(limits = c("m", "w"), values = c("skyblue1", "palevioletred1"), name = "Student Gender Preference", labels = c("Male", "Female")) +
  facet_wrap(~class)
  
test<-p_by_date %>% 
  filter(class == "210") 

  
ggplot(test, aes(x = date)) +
  geom_bar(aes(fill = student_g_p)) +
  scale_fill_manual(limits = c("m", "w"), values = c("skyblue1", "palevioletred1"), name = "Student Gender Preference", labels = c("Male", "Female")) +
  scale_x_date(breaks = as.Date(c("2018-10-01", "2018-10-08", "2018-10-15", "2018-10-22", "2018-10-29", "2018-11-05", "2018-11-12", "2018-11-19", "2018-11-26", "2018-12-03"))) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
  
```


###Model of probability of male/female participation

```{r}
#explore data a bit to see if there are relationships

q_a <- ggplot(w_p, aes(x = q_or_a)) +
  geom_bar(aes(color = student_g_p))
q_a

class <- ggplot(w_p, aes(x = class)) +
  geom_bar(aes(color = student_g_p))
class

prof <- ggplot(w_p, aes(x = prof_g_p)) +
  geom_bar(aes(color = student_g_p))
prof

time <- ggplot(w_p, aes(x = time)) +
  geom_bar(aes(color = student_g_p))
time


```


```{r}
#model exploration

#multiple linear regression with all variables
#gender_lm1 <- lm(student_g_p ~ class + time + prof_g_p + q_or_a, data = w_p)
#summary(gender_lm1) 
#not working maybe need to do a binary logistic regression because the result is not continuous

#binary logistic regression

#converting student_g_p to 1 and 0, w = 1 m = 0
w_p_binary <-w_p %>% 
  mutate(student_g_binary = recode(student_g_p, "w" = 1, "m" = 0)) %>% 
  select(date, class, professor, prof_g_p, q_or_a, student_g_p, time, student_g_binary)

#binary logistic model with all variables
#MODEL 1
gender_logmod1 <- glm(student_g_binary ~ class + time + prof_g_p + q_or_a, data = w_p_binary, family = "binomial")
gender_logmod1
summary(gender_logmod1)

#exploritory predictions of women precipitation with logistic model 1

#prediction of woman participation if in 203, first part class, woman professor, and question
earth_1 <- data.frame(class = "203", time = "1", prof_g_p = "w", q_or_a = "q") 
earth_1_logodds <- predict(gender_logmod1, newdata = earth_1, type = "link") #log odds of women participation
earth_1_odds <- exp(earth_1_logodds) #odds women participation
earth_1_prob <- predict(gender_logmod1, newdata = earth_1, type = "response")
earth_1_prob

#attempt predict probability with out dataframe




```


```{r}
#model visualization
earth_1_data <- as.data.frame(earth_1_prob)
prob_vis <- ggplot(earth_1_data) +
  geom_bar(aes(x = earth_1_prob))
#prob_vis
#this is not showing what I want it to show



```


###Contested Call

```{r}
con_df = w_p %>% 
  filter(cont_call == 1) %>% 
  mutate(prop_w = number_w_p/(number_w_p+number_m_p))

con_by_date <- con_df %>% 
  mutate(date = mdy(date)) %>% 
  select(date, student_g_p, class)

ggplot(con_by_date, aes(x = date)) +
  geom_bar(aes(fill = student_g_p)) +
  facet_wrap(~class)
```


```{r}

con_tally = con_df %>% 
  select(prof_g_p, q_or_a, student_g_p) %>% 
  group_by(prof_g_p, q_or_a, student_g_p) %>% 
  tally()

mosaic(table(con_tally), shade=TRUE, legend=FALSE)
```

Creating a proportion of how being contested changes probability 
```{r}

con_w_df = con_df %>% 
  filter(student_g_p == "w") %>% 
  filter(number_w_p == 1) %>% 
  filter(number_m_p == 1)

con_m_df = con_df %>% 
  filter(student_g_p == "m") %>% 
  filter(number_m_p == 1) %>% 
  filter(number_w_p == 1)


prop_w_con = count(con_w_df)/(count(con_w_df)+count(con_m_df))
#prop_w
prop_m_con_overall = count(con_m_df)/(count(con_w_df)+count(con_m_df))
#prop_m
prop_m_con_overall


```


```{r}

con_sing_df = con_df %>% 
  filter(number_m_p == 1) %>% 
  filter(number_w_p == 1)

con_mprof_df = con_df %>% 
  filter(number_m_p == 1) %>% 
  filter(number_w_p == 1) %>% 
  filter(prof_g_p == "m")

con_wprof_df = con_df %>% 
  filter(number_m_p == 1) %>% 
  filter(number_w_p == 1) %>% 
  filter(prof_g_p == "w")

con_w_df_prof = con_w_df %>% 
  filter(prof_g_p == "w") 

con_m_df_prof = con_w_df %>% 
  filter(prof_g_p == "m")


prop_w_con_prof_w = count(con_w_df_prof)/(count(con_wprof_df))
#prop_w
prop_m_con_prof_w = count(con_m_df_prof)/(count(con_mprof_df))
#prop_m
prop_m_con_prof_w

prop_w_con_prof_w

```



